//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculate_Amount
    {
        public string User_Id { get; set; }
        public string Class { get; set; }
        public int Total_No_Of_Seats { get; set; }
        public string PNR_No { get; set; }
        public int amount_id { get; set; }
    }
}
