//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger_Details
    {
        public string User_Id { get; set; }
        public string Passenger_Name1 { get; set; }
        public string Passenger_Name2 { get; set; }
        public string Passenger_Name3 { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public int Train_No { get; set; }
        public string Select_Seat_P1 { get; set; }
        public string Select_Seat_P2 { get; set; }
        public string Select_Seat_P3 { get; set; }
        public string Class { get; set; }
        public System.DateTime Date_Of_Booking { get; set; }
        public System.DateTime DOJ { get; set; }
        public int BookingId { get; set; }
        public int Total_No_Of_Seats { get; set; }
        public string PNR_No { get; set; }
    }
}
