//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Details
    {
        public long Card_No { get; set; }
        public string Card_Holder_Name { get; set; }
        public string Card_Type { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public int CVV { get; set; }
        public int Available_Balance { get; set; }
        public string UserId { get; set; }
    
        public virtual User_Details User_Details { get; set; }
    }
}
