//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search_Details
    {
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime DOJ { get; set; }
        public int id { get; set; }
    }
}
