//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Train_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train_Details()
        {
            this.Station = new HashSet<Station>();
        }
    
        public string Source { get; set; }
        public string Destination { get; set; }
        [Display(Name="Start Date")]
        public System.DateTime Start_Date { get; set; }
        [Display(Name = "End Date")]
        public System.DateTime End_Date { get; set; }
        [Display(Name = "Start Time")]
        public System.TimeSpan Start_Time { get; set; }
        [Display(Name = "End Time")]
        public System.TimeSpan End_Time { get; set; }
        [Display(Name = "Train Type")]
        public string Train_Type { get; set; }
        [Display(Name = "Train No")]
        public int Train_No { get; set; }
        [Display(Name = "Train Name")]
        public string Train_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station> Station { get; set; }
    }
}
